### PR TITLE
A Special PR...

### PR DESCRIPTION
**Pull request by CDAGaming**
This PR Merges all Changes from Upstream, as well as ports over 2 of the 3 Currently Open PRs, including yours, over to JDA.

Hopefully, this inspires you to continue this mod, as it does show some promise to it :D

### CODE REVIEW

**Comment by CDAGaming** [comment]
PS These PR Ports were made manually, so there shouldn't honestly be any real conflicts here.

**Comment by Mohron** [comment]
If your interested in continuing this project, you'd be better off maintaining your own fork or trying to get your changes merged upstream. I've moved on to other projects and don't really have a need for DiscordBridge anymore. Also, in Hy's absence, MagiBridge has gathered a lot of steam and I'm not even sure if DiscordBridge will ever be relevant again in its current state. You're welcome to merge any commit from my repo into yours (including other branches) if you decide to continue this yourself. Sorry to disappoint.

**Comment by CDAGaming** [comment]
I looked at MagiBridge, and it seems that this PR is mostly equivalent to what MagiBridge already has. I'll still try to merge these upstream though.

**Comment by Mohron** [comment]
I personally wouldn't use magi bridge but I know a lot of people have moved to it.

**Pull request closed without merging**
